# Generated by Django 5.2.6 on 2025-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
    ]
