# Generated by Django 5.2.6 on 2025-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(),
        ),
    ]
