# Generated by Django 5.2.6 on 2025-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione Facultad --'), ('FIE', 'Facultad de Informática y Electrónica'), ('FADE', 'Facultad Administración de Empresas'), ('FCS', 'Facultad de Ciencias'), ('FCP', 'Facultad de Ciencias Pecuarias'), ('FME', 'Facultad de Mecánica'), ('FNR', 'Facultad de Recursos Naturales'), ('FSP', 'Facultad de Salud Pública')], max_length=20, null=True, verbose_name='Facultad'),
        ),
    ]
